---
title: "README"
author: "Gustavo Niño"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting and Cleaning Data

This is a README document with organized data from "Human Activity Recognition Using Smartphones Dataset", as part of Coursera and Johns Hopkins University course "Getting and Cleaning Data"  <https://www.coursera.org/learn/data-cleaning/home/welcome>.

The original Dataset includes the following files:
=========================================

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 
=========================================


The processing done over the datasets, consists in the creation of one single tidy dataset that combines and properly labels the training and test data sets, with additional processing, folowing this steps:

  1.  Merges the training and the test sets to create one data set.

  2. Uses descriptive activity names to name the activities in the data set

  3. Extracts only the measurements on the mean and standard deviation for each measurement. 

  4. Appropriately labels the data set with descriptive variable names. 

  5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
  
The R script used goes by the name of "run_analysis.R" and generates the "tidy_data.txt" file.

License:
========
Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

[2] "run_analysis.R", "tidy_data.txt", "README.Rmd", "Codebook.Rmd" where created by Gustavo Niño, as part of the Getting and Cleaning Data project for coursera course. Contact the Author on gustavo.a.nino@gmail.com.